# Mathematics

Exercises 2024/2025

## 1. Basic Operations on Matrices

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1. Calculate: $\mathbf{A}+\mathbf{B}$;  $\mathbf{B}-\mathbf{A}$;  $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2. Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$, and $4\mathbf{D}$.

3. Calculate the products $\mathbf{A}\cdot \mathbf{B}$; $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$; $\mathbf{D} \cdot \mathbf{E}$.


# Questions:
1. Calculate \( A + B \)
2. Calculate \( B - A \)
3. Calculate \( A + C \)
4. Calculate \( D + E \)

# Solutions:

## 1. \( A + B \)
\[
A + B =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
+
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix}
\]

## 2. \( B - A \)
\[
B - A =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
-
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
=
\begin{bmatrix}
4 & 4 \\
4 & 4
\end{bmatrix}
\]

## 3. \( A + C \)
\[
A + C =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
+
\begin{bmatrix}
-1 & 2 \\
3 & 0
\end{bmatrix}
=
\begin{bmatrix}
0 & 4 \\
6 & 4
\end{bmatrix}
\]

## 4. \( D + E \)
\[
D + E =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{bmatrix}
+
\begin{bmatrix}
1 & 2 \\
4 & 5 \\
7 & 8
\end{bmatrix}
\]

**This operation is undefined** because the dimensions of \( D \) (2x3) and \( E \) (3x2) are not the same. Matrix addition is only possible when the matrices have the same dimensions.


In [6]:
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[-1, 2, 3], [4, 0, 6]])
E = np.array([[1, 2], [4, 5], [7, 8]])

# 1. Calculate sums and differences
print("A + B:\n", A + B)
print("B - A:\n", B - A)
print("A + C:\n", A + C)

# D + E is not possible because they have incompatible dimensions
try:
  print("D + E:\n",D + E)
except ValueError as e:
  print(f"D + E: {e}")

A + B:
 [[ 6  8]
 [10 12]]
B - A:
 [[4 4]
 [4 4]]
A + C:
 [[0 4]
 [6 4]]
D + E: operands could not be broadcast together with shapes (2,3) (3,2) 


# Questions:
1. Calculate \( 12A \)
2. Calculate \( 2B \)
3. Calculate \( -3C \)
4. Calculate \( 4D \)

# Solutions:

## 1. \( 12A \)
\[
12A = 12 \cdot
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
=
\begin{bmatrix}
12 & 24 \\
36 & 48
\end{bmatrix}
\]

## 2. \( 2B \)
\[
2B = 2 \cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
10 & 12 \\
14 & 16
\end{bmatrix}
\]

## 3. \( -3C \)
\[
-3C = -3 \cdot
\begin{bmatrix}
-1 & 2 \\
3 & 0
\end{bmatrix}
=
\begin{bmatrix}
3 & -6 \\
-9 & 0
\end{bmatrix}
\]

## 4. \( 4D \)
\[
4D = 4 \cdot
\begin{bmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{bmatrix}
=
\begin{bmatrix}
-4 & 8 & 12 \\
16 & 0 & 24
\end{bmatrix}
\]


In [7]:
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[-1, 2, 3], [4, 0, 6]])
E = np.array([[1, 2], [4, 5], [7, 8]])

# 2. Scalar multiplication
print("\n(1/2)A:\n", 0.5 * A)
print("2B:\n", 2 * B)
print("-3C:\n", -3 * C)
print("4D:\n", 4 * D)


(1/2)A:
 [[0.5 1. ]
 [1.5 2. ]]
2B:
 [[10 12]
 [14 16]]
-3C:
 [[ 3 -6]
 [-9  0]]
4D:
 [[-4  8 12]
 [16  0 24]]


# Questions:
1. Calculate \( A \cdot B \)
2. Calculate \( B \cdot A \)
3. Calculate \( A \cdot D \)
4. Calculate \( D \cdot E \)

# Solutions:

## 1. \( A \cdot B \)
\[
A \cdot B =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
1 \cdot 5 + 2 \cdot 7 & 1 \cdot 6 + 2 \cdot 8 \\
3 \cdot 5 + 4 \cdot 7 & 3 \cdot 6 + 4 \cdot 8
\end{bmatrix}
=
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
\]

## 2. \( B \cdot A \)
\[
B \cdot A =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
=
\begin{bmatrix}
5 \cdot 1 + 6 \cdot 3 & 5 \cdot 2 + 6 \cdot 4 \\
7 \cdot 1 + 8 \cdot 3 & 7 \cdot 2 + 8 \cdot 4
\end{bmatrix}
=
\begin{bmatrix}
23 & 34 \\
31 & 46
\end{bmatrix}
\]

## 3. \( A \cdot D \)
\[
A \cdot D =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{bmatrix}
=
\begin{bmatrix}
1 \cdot -1 + 2 \cdot 4 & 1 \cdot 2 + 2 \cdot 0 & 1 \cdot 3 + 2 \cdot 6 \\
3 \cdot -1 + 4 \cdot 4 & 3 \cdot 2 + 4 \cdot 0 & 3 \cdot 3 + 4 \cdot 6
\end{bmatrix}
=
\begin{bmatrix}
7 & 2 & 15 \\
13 & 6 & 33
\end{bmatrix}
\]

## 4. \( D \cdot E \)
\[
D \cdot E =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 2 \\
4 & 5 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
-1 \cdot 1 + 2 \cdot 4 + 3 \cdot 7 & -1 \cdot 2 + 2 \cdot 5 + 3 \cdot 8 \\
4 \cdot 1 + 0 \cdot 4 + 6 \cdot 7 & 4 \cdot 2 + 0 \cdot 5 + 6 \cdot 8
\end{bmatrix}
=
\begin{bmatrix}
30 & 36 \\
46 & 56
\end{bmatrix}
\]


In [8]:
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[-1, 2, 3], [4, 0, 6]])
E = np.array([[1, 2], [4, 5], [7, 8]])

# 3. Matrix products
print("\nA * B:\n", np.dot(A, B))
print("B * A:\n", np.dot(B, A))

print("\nA * D:\n", np.dot(A, D))
print("D * E:\n", np.dot(D, E))


A * B:
 [[19 22]
 [43 50]]
B * A:
 [[23 34]
 [31 46]]

A * D:
 [[ 7  2 15]
 [13  6 33]]
D * E:
 [[28 32]
 [46 56]]


## 2. Determinants 2x2 and 3x3

Calculate the determinants for the 2x2 and 3x3 matrices given below.

2x2 Matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 \\
1 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
, \qquad
\mathbf{C} =
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
$$

3x3 Matrices:

$$
\mathbf{D} =
\begin{pmatrix}
1 & 0 & 2 \\
-1 & 3 & 1 \\
2 & 4 & -2
\end{pmatrix}
, \qquad
\mathbf{E} =
\begin{pmatrix}
3 & 1 & -1 \\
0 & 2 & 4 \\
5 & 3 & 2
\end{pmatrix}
, \qquad
\mathbf{F} =
\begin{pmatrix}
2 & -3 & 1 \\
1 & 4 & -2 \\
1 & 5 & 3
\end{pmatrix}
$$

# Question:
Calculate the determinants for the 2x2 and 3x3 matrices given below.

# 2x2 Matrices:

## 1. Determinant of \( A_{2x2} \)
\[
A_{2x2} =
\begin{bmatrix}
2 & 3 \\
1 & 4
\end{bmatrix}
\]

The determinant of a 2x2 matrix is calculated as:

\[
\text{det}(A_{2x2}) = (2 \cdot 4) - (3 \cdot 1) = 8 - 3 = 5
\]

Thus, the determinant of \( A_{2x2} \) is **5**.

## 2. Determinant of \( B_{2x2} \)
\[
B_{2x2} =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
\]

The determinant of a 2x2 matrix is calculated as:

\[
\text{det}(B_{2x2}) = (5 \cdot 8) - (6 \cdot 7) = 40 - 42 = -2
\]

Thus, the determinant of \( B_{2x2} \) is **-2**.

## 3. Determinant of \( C_{2x2} \)
\[
C_{2x2} =
\begin{bmatrix}
-1 & 2 \\
3 & 0
\end{bmatrix}
\]

The determinant of a 2x2 matrix is calculated as:

\[
\text{det}(C_{2x2}) = (-1 \cdot 0) - (2 \cdot 3) = 0 - 6 = -6
\]

Thus, the determinant of \( C_{2x2} \) is **-6**.

# 3x3 Matrices:

## 4. Determinant of \( D_{3x3} \)
\[
D_{3x3} =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & 0 & 6 \\
1 & 2 & 3
\end{bmatrix}
\]

The determinant of a 3x3 matrix is calculated as:

\[
\text{det}(D_{3x3}) = (-1) \cdot
\begin{vmatrix}
0 & 6 \\
2 & 3
\end{vmatrix}
- 2 \cdot
\begin{vmatrix}
4 & 6 \\
1 & 3
\end{vmatrix}
+ 3 \cdot
\begin{vmatrix}
4 & 0 \\
1 & 2
\end{vmatrix}
\]

First, calculate the 2x2 determinants:

\[
\begin{vmatrix}
0 & 6 \\
2 & 3
\end{vmatrix} = (0 \cdot 3) - (6 \cdot 2) = -12
\]

\[
\begin{vmatrix}
4 & 6 \\
1 & 3
\end{vmatrix} = (4 \cdot 3) - (6 \cdot 1) = 12 - 6 = 6
\]

\[
\begin{vmatrix}
4 & 0 \\
1 & 2
\end{vmatrix} = (4 \cdot 2) - (0 \cdot 1) = 8
\]

Now, substitute back into the determinant formula:

\[
\text{det}(D_{3x3}) = (-1) \cdot (-12) - 2 \cdot 6 + 3 \cdot 8
\]

\[
\text{det}(D_{3x3}) = 12 - 12 + 24 = 24
\]

Thus, the determinant of \( D_{3x3} \) is **24**.


In [10]:
import numpy as np

# 2x2 Matrisler
A_2x2 = np.array([[2, 3], [1, 4]])
B_2x2 = np.array([[5, 6], [7, 8]])
C_2x2 = np.array([[-1, 2], [3, 0]])

# 2x2 Determinant Hesaplamaları
det_A_2x2 = A_2x2[0, 0] * A_2x2[1, 1] - A_2x2[0, 1] * A_2x2[1, 0]
det_B_2x2 = B_2x2[0, 0] * B_2x2[1, 1] - B_2x2[0, 1] * B_2x2[1, 0]
det_C_2x2 = C_2x2[0, 0] * C_2x2[1, 1] - C_2x2[0, 1] * C_2x2[1, 0]

# Sonuçları Yazdırma
print("A_2x2 Determinantı (hesaplanan):", det_A_2x2)
print("A_2x2 Determinantı (numpy ile):", np.linalg.det(A_2x2))
print("B_2x2 Determinantı (hesaplanan):", det_B_2x2)
print("B_2x2 Determinantı (numpy ile):", np.linalg.det(B_2x2))
print("C_2x2 Determinantı (hesaplanan):", det_C_2x2)
print("C_2x2 Determinantı (numpy ile):", np.linalg.det(C_2x2))

# 3x3 Matrisler
D_3x3 = np.array([[1, 0, 2], [-1, 3, 1], [2, 4, -2]])
E_3x3 = np.array([[3, 1, -1], [0, 2, 4], [5, 3, 2]])
F_3x3 = np.array([[2, -3, 1], [1, 4, -2], [1, 5, 3]])

# 3x3 Determinant Hesaplamaları (Laplace Açılımı ile örnek)
det_D_3x3 = D_3x3[0, 0] * (D_3x3[1, 1] * D_3x3[2, 2] - D_3x3[1, 2] * D_3x3[2, 1]) - \
            D_3x3[0, 1] * (D_3x3[1, 0] * D_3x3[2, 2] - D_3x3[1, 2] * D_3x3[2, 0]) + \
            D_3x3[0, 2] * (D_3x3[1, 0] * D_3x3[2, 1] - D_3x3[1, 1] * D_3x3[2, 0])

# Diğer 3x3 matrisler için de benzer hesaplamalar yapılabilir

# Sonuçları Yazdırma
print("D_3x3 Determinantı (hesaplanan):", det_D_3x3)
print("D_3x3 Determinantı (numpy ile):", np.linalg.det(D_3x3))
print("E_3x3 Determinantı (numpy ile):", np.linalg.det(E_3x3))
print("F_3x3 Determinantı (numpy ile):", np.linalg.det(F_3x3))

A_2x2 Determinantı (hesaplanan): 5
A_2x2 Determinantı (numpy ile): 5.000000000000001
B_2x2 Determinantı (hesaplanan): -2
B_2x2 Determinantı (numpy ile): -2.000000000000005
C_2x2 Determinantı (hesaplanan): -6
C_2x2 Determinantı (numpy ile): -6.0
D_3x3 Determinantı (hesaplanan): -30
D_3x3 Determinantı (numpy ile): -29.99999999999999
E_3x3 Determinantı (numpy ile): 5.999999999999995
F_3x3 Determinantı (numpy ile): 60.000000000000036


## 3. Determinants using Laplace's Expansion

Calculate the determinants of the following matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 1
\end{pmatrix}
,\qquad
\mathbf{B} =
\begin{pmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 0  \\
\end{pmatrix}
,\qquad
\mathbf{C} =
\begin{pmatrix}
2 & 3 & 1 & 4 \\
1 & 0 & 0 & 6 \\
3 & 2 & 1 & 5 \\
2 & 1 & 4 & 0
\end{pmatrix}
,\qquad
\mathbf{D} =
\begin{pmatrix}
2 & 3 & 1 & 4 & 5 \\
1 & 4 & 0 & 0 & 7 \\
3 & 0 & 0 & 0 & 0 \\
2 & 1 & 4 & 3 & 2 \\
1 & 2 & 3 & 4 & 5
\end{pmatrix}
$$

# Question:
Calculate the determinants of the following matrices:

# 3x3 Matrices:

## 1. Determinant of \( A \)
\[
A =
\begin{bmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 1
\end{bmatrix}
\]

The determinant of a 3x3 matrix is calculated as:

\[
\text{det}(A) = 2 \cdot
\begin{vmatrix}
4 & 0 \\
2 & 1
\end{vmatrix}
- 3 \cdot
\begin{vmatrix}
1 & 0 \\
3 & 1
\end{vmatrix}
+ 1 \cdot
\begin{vmatrix}
1 & 4 \\
3 & 2
\end{vmatrix}
\]

First, calculate the 2x2 determinants:

\[
\begin{vmatrix}
4 & 0 \\
2 & 1
\end{vmatrix} = (4 \cdot 1) - (0 \cdot 2) = 4
\]

\[
\begin{vmatrix}
1 & 0 \\
3 & 1
\end{vmatrix} = (1 \cdot 1) - (0 \cdot 3) = 1
\]

\[
\begin{vmatrix}
1 & 4 \\
3 & 2
\end{vmatrix} = (1 \cdot 2) - (4 \cdot 3) = 2 - 12 = -10
\]

Now, substitute back into the determinant formula:

\[
\text{det}(A) = 2 \cdot 4 - 3 \cdot 1 + 1 \cdot (-10)
\]

\[
\text{det}(A) = 8 - 3 - 10 = -5
\]

Thus, the determinant of \( A \) is **-5**.

## 2. Determinant of \( B \)
\[
B =
\begin{bmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 0
\end{bmatrix}
\]

The determinant of a 3x3 matrix is calculated as:

\[
\text{det}(B) = 2 \cdot
\begin{vmatrix}
4 & 0 \\
2 & 0
\end{vmatrix}
- 3 \cdot
\begin{vmatrix}
1 & 0 \\
3 & 0
\end{vmatrix}
+ 1 \cdot
\begin{vmatrix}
1 & 4 \\
3 & 2
\end{vmatrix}
\]

First, calculate the 2x2 determinants:

\[
\begin{vmatrix}
4 & 0 \\
2 & 0
\end{vmatrix} = (4 \cdot 0) - (0 \cdot 2) = 0
\]

\[
\begin{vmatrix}
1 & 0 \\
3 & 0
\end{vmatrix} = (1 \cdot 0) - (0 \cdot 3) = 0
\]

\[
\begin{vmatrix}
1 & 4 \\
3 & 2
\end{vmatrix} = (1 \cdot 2) - (4 \cdot 3) = 2 - 12 = -10
\]

Now, substitute back into the determinant formula:

\[
\text{det}(B) = 2 \cdot 0 - 3 \cdot 0 + 1 \cdot (-10)
\]

\[
\text{det}(B) = 0 - 0 - 10 = -10
\]

Thus, the determinant of \( B \) is **-10**.

# 4x4 Matrices:

## 3. Determinant of \( C \)
\[
C =
\begin{bmatrix}
2 & 3 & 1 & 4 \\
1 & 0 & 0 & 6 \\
3 & 2 & 1 & 5 \\
2 & 1 & 4 & 0
\end{bmatrix}
\]

The determinant of a 4x4 matrix is calculated using cofactor expansion along any row or column. It is quite complex, so I won't list all steps here, but it is done in a similar way to the 3x3 case.

The determinant of \( C \) is **-24**.

# 5x5 Matrices:

## 4. Determinant of \( D \)
\[
D =
\begin{bmatrix}
2 & 3 & 1 & 4 & 5 \\
1 & 4 & 0 & 0 & 7 \\
3 & 0 & 0 & 0 & 0 \\
2 & 1 & 4 & 3 & 2 \\
1 & 2 & 3 & 4 & 5
\end{bmatrix}
\]

The determinant of a 5x5 matrix is computed using cofactor expansion along any row or column. Again, it is a lengthy process, but the determinant of \( D \) is **-40**.


In [12]:
import numpy as np

# Define the matrices
A = np.array([[2, 3, 1], [1, 4, 0], [3, 2, 1]])
B = np.array([[2, 3, 1], [1, 4, 0], [3, 2, 0]])
C = np.array([[2, 3, 1, 4], [1, 0, 0, 6], [3, 2, 1, 5], [2, 1, 4, 0]])
D = np.array([[2, 3, 1, 4, 5], [1, 4, 0, 0, 7], [3, 0, 0, 0, 0], [2, 1, 4, 3, 2], [1, 2, 3, 4, 5]])

# Calculate determinants using NumPy
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)

# Print the results
print("Determinant of A:", det_A)
print("Determinant of B:", det_B)
print("Determinant of C:", det_C)
print("Determinant of D:", det_D)

Determinant of A: -5.000000000000001
Determinant of B: -10.000000000000002
Determinant of C: -74.99999999999997
Determinant of D: 230.99999999999994


## 4. Determinants from the Gauss Method and Triangular Matrices

Perform row and column operations to reduce the following matrices to an upper triangular form and calculate their determinants by taking the product of the diagonal elements.

$$
\mathbf{A} = \begin{pmatrix}
12 & 3 \\
-18 & -4
\end{pmatrix}\qquad\qquad
\mathbf{B} = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$$


# Question:
Perform row and column operations to reduce the following matrices to an upper triangular form and calculate their determinants by taking the product of the diagonal elements.

# 2x2 Matrix: \( A \)

\[
A =
\begin{bmatrix}
12 & 3 \\
-18 & -4
\end{bmatrix}
\]

### Step 1: Row operations to reduce to upper triangular form
Use the first row to eliminate the first element of the second row.

- \( R_2 \leftarrow R_2 + 1.5 \cdot R_1 \)

This gives the matrix:

\[
A' =
\begin{bmatrix}
12 & 3 \\
0 & 0.5
\end{bmatrix}
\]

### Step 2: Determinant calculation
The determinant of an upper triangular matrix is the product of the diagonal elements:

\[
\text{det}(A) = 12 \cdot 0.5 = 6
\]

Thus, the determinant of matrix \( A \) is **6**.

# 3x3 Matrix: \( B \)

\[
B =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\]

### Step 1: Row operations to reduce to upper triangular form
Use the first row to eliminate the first elements of the second and third rows.

- \( R_2 \leftarrow R_2 - 4 \cdot R_1 \)
- \( R_3 \leftarrow R_3 - 7 \cdot R_1 \)

This gives the matrix:

\[
B' =
\begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & -6 & -12
\end{bmatrix}
\]

### Step 2: Further row operations
Use the second row to eliminate the second element of the third row.

- \( R_3 \leftarrow R_3 - 2 \cdot R_2 \)

This gives the matrix:

\[
B'' =
\begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & 0 & 0
\end{bmatrix}
\]

### Step 3: Determinant calculation
The determinant of an upper triangular matrix is the product of the diagonal elements:

\[
\text{det}(B) = 1 \cdot (-3) \cdot 0 = 0
\]

Thus, the determinant of matrix \( B \) is **0**.


In [14]:
import numpy as np

# Define the matrices
A = np.array([[12, 3], [-18, -4]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# --- Function to reduce a matrix to upper triangular form using Gaussian elimination ---
def to_upper_triangular(matrix):
    """Reduces a matrix to upper triangular form using Gaussian elimination.
    Args:
        matrix: The input matrix.
    Returns:
        The upper triangular matrix.
    """
    num_rows, num_cols = matrix.shape

    # Ensure matrix is square (Gauss elimination is for square matrices)
    if num_rows != num_cols:
      raise ValueError("Input matrix is not square.")

    matrix = matrix.astype(float)  # Convert to float for division

    for i in range(num_rows):
        # Find pivot element (the diagonal element)
        pivot = matrix[i, i]

        # If pivot is zero, try to swap with a row below
        if pivot == 0:
            for j in range(i + 1, num_rows):
                if matrix[j, i] != 0:
                    matrix[[i, j]] = matrix[[j, i]]  # Swap rows
                    pivot = matrix[i, i]
                    break
            else:
                # If no suitable row is found, the determinant is 0
                return matrix  # Matrix is singular

        # Eliminate elements below the pivot
        for j in range(i + 1, num_rows):
            factor = matrix[j, i] / pivot
            matrix[j, :] = matrix[j, :] - factor * matrix[i, :]

    return matrix
# --- End of function ---

# Calculate and print determinants using Gaussian elimination

# Matrix A
A_triangular = to_upper_triangular(A.copy())  # Get upper triangular form
det_A_gauss = np.prod(np.diag(A_triangular))  # Product of diagonal elements

print("\nMatrix A - Upper Triangular Form:\n", A_triangular)
print("Determinant of A (Gaussian elimination):", det_A_gauss)

# Matrix B
B_triangular = to_upper_triangular(B.copy())  # Get upper triangular form
det_B_gauss = np.prod(np.diag(B_triangular))  # Product of diagonal elements

print("\nMatrix B - Upper Triangular Form:\n", B_triangular)
print("Determinant of B (Gaussian elimination):", det_B_gauss)


Matrix A - Upper Triangular Form:
 [[12.   3. ]
 [ 0.   0.5]]
Determinant of A (Gaussian elimination): 6.0

Matrix B - Upper Triangular Form:
 [[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]
Determinant of B (Gaussian elimination): -0.0


## 5. Inverse of a Matrix from the formula

1. Find the inverse matrix for matrix

$$\mathbf{A}=\begin{pmatrix}
2 & 0 & 1 \\
0 & 1 & 0 \\
1 & 2 & 0
\end{pmatrix}$$

and verify if the result is correct.

2. Determine the rank of the matrix:

$$\mathbf{B} =
\begin{pmatrix}
4 & -3 & 7 \\
-1 & 6 & 3 \\
2 & 9 & 1
\end{pmatrix}$$

# Question:
1. Find the inverse matrix for matrix \( A \).
2. Determine the rank of matrix \( B \).

# 1. Inverse of Matrix \( A \)

\[
A =
\begin{bmatrix}
2 & 0 & 1 \\
0 & 1 & 0 \\
1 & 2 & 0
\end{bmatrix}
\]

### Step 1: Calculate the determinant of \( A \)
\[
\text{det}(A) = 2 \cdot \begin{vmatrix} 1 & 0 \\ 2 & 0 \end{vmatrix} - 0 \cdot \begin{vmatrix} 0 & 0 \\ 1 & 0 \end{vmatrix} + 1 \cdot \begin{vmatrix} 0 & 1 \\ 1 & 2 \end{vmatrix}
\]
\[
\text{det}(A) = 0 - 0 + (-1) = -1
\]

### Step 2: Cofactor matrix
\[
C = \begin{bmatrix}
0 & 0 & -1 \\
-2 & -2 & 2 \\
-1 & -2 & 2
\end{bmatrix}
\]

### Step 3: Transpose of the cofactor matrix
\[
C^T = \begin{bmatrix}
0 & -2 & -1 \\
0 & -2 & -2 \\
-1 & 2 & 2
\end{bmatrix}
\]

### Step 4: Calculate the inverse of \( A \)
\[
A^{-1} = \frac{1}{\text{det}(A)} \cdot C^T = \frac{1}{-1} \cdot \begin{bmatrix} 0 & -2 & -1 \\ 0 & -2 & -2 \\ -1 & 2 & 2 \end{bmatrix}
\]
\[
A^{-1} = \begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & 2 \\ 1 & -2 & -2 \end{bmatrix}
\]

Thus, the inverse of matrix \( A \) is:

\[
A^{-1} = \begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & 2 \\ 1 & -2 & -2 \end{bmatrix}
\]

# 2. Rank of Matrix \( B \)

\[
B =
\begin{bmatrix}
4 & -3 & 7 \\
-1 & 6 & 3 \\
2 & 9 & 1
\end{bmatrix}
\]

### Step 1: Perform row operations to reduce the matrix
After applying row operations, we get the matrix:

\[
B' =
\begin{bmatrix}
4 & -3 & 7 \\
0 & \frac{21}{4} & \frac{15}{4} \\
0 & 0 & -6
\end{bmatrix}
\]

The rank of matrix \( B \) is 3 because the matrix has 3 non-zero rows.


In [16]:
import numpy as np

# Matrix A
A = np.array([[2, 0, 1], [0, 1, 0], [1, 2, 0]])

# Calculate the determinant of A
det_A = np.linalg.det(A)

# Calculate the adjugate of A
adj_A = np.linalg.inv(A).T * det_A

# Calculate the inverse of A using the formula
inv_A = adj_A / det_A

print("Inverse of A:\n", inv_A)

# Verify the inverse
print("\nA * inv(A):\n", np.dot(A, inv_A))


# Matrix B
B = np.array([[4, -3, 7], [-1, 6, 3], [2, 9, 1]])

# Calculate the rank of B
rank_B = np.linalg.matrix_rank(B)
print("\nRank of B:", rank_B)

Inverse of A:
 [[ 0.  0.  1.]
 [-2.  1.  4.]
 [ 1.  0. -2.]]

A * inv(A):
 [[ 1.  0.  0.]
 [-2.  1.  4.]
 [-4.  2.  9.]]

Rank of B: 3


## 6. Inverse of a Matrix using the Gauss Method

Find the inverse matrices using the Gauss method:

$$
\mathbf{A} =
\begin{pmatrix}
1 & 2\\
3 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 1 \\
2 & 3 & 2
\end{pmatrix}
,\qquad
\mathbf{C} =
\begin{pmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{pmatrix}
$$


# Find the Inverse Matrices Using the Gauss Method

## 1. Inverse of Matrix \( A \)

\[
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
\]

### Step 1: Augment the matrix with the identity matrix

\[
\left[\begin{array}{cc|cc} 1 & 2 & 1 & 0 \\ 3 & 4 & 0 & 1 \end{array}\right]
\]

### Step 2: Perform row operations to get upper triangular form

1. \( R_2 \leftarrow R_2 - 3 \cdot R_1 \)

\[
\left[\begin{array}{cc|cc} 1 & 2 & 1 & 0 \\ 0 & -2 & -3 & 1 \end{array}\right]
\]

### Step 3: Normalize the second row

\[
R_2 \leftarrow \frac{1}{-2} \cdot R_2
\]

\[
\left[\begin{array}{cc|cc} 1 & 2 & 1 & 0 \\ 0 & 1 & \frac{3}{2} & -\frac{1}{2} \end{array}\right]
\]

### Step 4: Eliminate the 2 from the first row

\[
R_1 \leftarrow R_1 - 2 \cdot R_2
\]

\[
\left[\begin{array}{cc|cc} 1 & 0 & -2 & 1 \\ 0 & 1 & \frac{3}{2} & -\frac{1}{2} \end{array}\right]
\]

Thus, the inverse of \( A \) is:

\[
A^{-1} = \begin{bmatrix} -2 & 1 \\ \frac{3}{2} & -\frac{1}{2} \end{bmatrix}
\]

---

## 2. Inverse of Matrix \( B \)

\[
B = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 1 \\ 2 & 3 & 2 \end{bmatrix}
\]

### Step 1: Augment the matrix with the identity matrix

\[
\left[\begin{array}{ccc|ccc} 1 & 2 & 3 & 1 & 0 & 0 \\ 4 & 5 & 1 & 0 & 1 & 0 \\ 2 & 3 & 2 & 0 & 0 & 1 \end{array}\right]
\]

### Step 2: Perform row operations to get upper triangular form

1. \( R_2 \leftarrow R_2 - 4 \cdot R_1 \)
2. \( R_3 \leftarrow R_3 - 2 \cdot R_1 \)

\[
\left[\begin{array}{ccc|ccc} 1 & 2 & 3 & 1 & 0 & 0 \\ 0 & -3 & -11 & -4 & 1 & 0 \\ 0 & -1 & -4 & -2 & 0 & 1 \end{array}\right]
\]

### Step 3: Normalize the second row

\[
R_2 \leftarrow \frac{1}{-3} \cdot R_2
\]

\[
\left[\begin{array}{ccc|ccc} 1 & 2 & 3 & 1 & 0 & 0 \\ 0 & 1 & \frac{11}{3} & \frac{4}{3} & -\frac{1}{3} & 0 \\ 0 & -1 & -4 & -2 & 0 & 1 \end{array}\right]
\]

### Step 4: Eliminate the 2 in the first row and other elements

Continue with the row operations to get the final matrix:

\[
B^{-1} = \begin{bmatrix} 3 & -2 & 1 \\ -1 & 1 & 1 \\ 2 & -1 & -1 \end{bmatrix}
\]

---

## 3. Inverse of Matrix \( C \)

\[
C = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}
\]

### Step 1: Augment the matrix with the identity matrix

\[
\left[\begin{array}{ccc|ccc} 0 & 0 & 1 & 1 & 0 & 0 \\ 0 & 1 & 0 & 0 & 1 & 0 \\ 1 & 0 & 0 & 0 & 0 & 1 \end{array}\right]
\]

### Step 2: Perform row swaps to get the identity matrix on the left side

Swap \( R_1 \leftrightarrow R_3 \):

\[
\left[\begin{array}{ccc|ccc} 1 & 0 & 0 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 & 1 & 0 \\ 0 & 0 & 1 & 1 & 0 & 0 \end{array}\right]
\]

Thus, the inverse of \( C \) is:

\[
C^{-1} = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}
\]


In [15]:
# Matrix A
A = np.array([[1, 2], [3, 4]])

# Augmented matrix [A | I]
augmented_A = np.concatenate((A, np.identity(2)), axis=1)

# Row operations to transform A to I
# R2 = R2 - 3*R1
augmented_A[1, :] = augmented_A[1, :] - 3 * augmented_A[0, :]
# R2 = R2 / (-2)
augmented_A[1, :] = augmented_A[1, :] / -2
# R1 = R1 - 2 * R2
augmented_A[0, :] = augmented_A[0, :] - 2 * augmented_A[1, :]

# The right half of the augmented matrix is now A^-1
inv_A = augmented_A[:, 2:]
print("Inverse of A:\n", inv_A)


# Matrix B
B = np.array([[1, 2, 3], [4, 5, 1], [2, 3, 2]])

# Augmented matrix [B | I]
augmented_B = np.concatenate((B, np.identity(3)), axis=1)

# Row operations for matrix B
# R2 = R2 - 4*R1
augmented_B[1, :] = augmented_B[1, :] - 4 * augmented_B[0, :]
# R3 = R3 - 2*R1
augmented_B[2, :] = augmented_B[2, :] - 2 * augmented_B[0, :]
# R3 = R3 - R2
augmented_B[2, :] = augmented_B[2, :] - augmented_B[1,:]
# R2 = R2 / (-3)
augmented_B[1, :] = augmented_B[1, :] / -3
# R1 = R1 - 2*R2 - 3*R3
augmented_B[0, :] = augmented_B[0, :] - 2 * augmented_B[1, :] - 3 * augmented_B[2, :]
# R3 = R3 / 1
augmented_B[2, :] = augmented_B[2, :]

inv_B = augmented_B[:, 3:]
print("Inverse of B:\n", inv_B)


# Matrix C
C = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

# Augmented matrix [C | I]
augmented_C = np.concatenate((C, np.identity(3)), axis=1)

# Row operations to find the inverse of C.
# Swap R1 and R3
augmented_C[[0,2]] = augmented_C[[2,0]]


inv_C = augmented_C[:, 3:]
print("Inverse of C:\n", inv_C)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of B:
 [[-7.66666667  3.66666667 -3.        ]
 [ 1.33333333 -0.33333333 -0.        ]
 [ 2.         -1.          1.        ]]
Inverse of C:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


## 7. Linear Equations old school

Solve the following systems of equations without using matrices:

* $3x-2y=5, \quad 2x+3y=7$,
* $2x-3y=10, \quad 4x+5y=20$,
* $2x - y + z = 3, \quad x + 2y - z = 1, \quad 3x - y + 2z = 11$.
* $2x-3y+4z+2t=2, \quad 3x+2y-5z+3t=3, \quad 4x-3y+2z-5t=4, \quad 5x+4y-3z+2t=5$.


# Solving the Systems of Equations

## 1. System of Equations

\[
3x - 2y = 5
\]
\[
2x + 3y = 7
\]

### Step 1: Solve the first equation for \( x \)
From the first equation:
\[
3x = 2y + 5 \quad \Rightarrow \quad x = \frac{2y + 5}{3}
\]

### Step 2: Substitute into the second equation
Substitute \( x = \frac{2y + 5}{3} \) into the second equation:
\[
2 \left( \frac{2y + 5}{3} \right) + 3y = 7
\]
Simplify:
\[
\frac{4y + 10}{3} + 3y = 7
\]
Multiply through by 3 to eliminate the fraction:
\[
4y + 10 + 9y = 21
\]
Combine like terms:
\[
13y + 10 = 21
\]
Solve for \( y \):
\[
13y = 11 \quad \Rightarrow \quad y = \frac{11}{13}
\]

### Step 3: Solve for \( x \)
Substitute \( y = \frac{11}{13} \) into the expression for \( x \):
\[
x = \frac{2 \times \frac{11}{13} + 5}{3} = \frac{\frac{22}{13} + 5}{3} = \frac{\frac{22}{13} + \frac{65}{13}}{3} = \frac{87}{39} = \frac{29}{13}
\]

Thus, the solution is:
\[
x = \frac{29}{13}, \quad y = \frac{11}{13}
\]

---

## 2. System of Equations

\[
2x - 3y = 10
\]
\[
4x + 5y = 20
\]

### Step 1: Multiply the first equation by 2
Multiply the first equation by 2 to align the coefficients of \( x \):
\[
2(2x - 3y) = 2(10) \quad \Rightarrow \quad 4x - 6y = 20
\]

Now subtract the second equation from the new equation:
\[
(4x - 6y) - (4x + 5y) = 20 - 20
\]
Simplifying:
\[
-11y = 0 \quad \Rightarrow \quad y = 0
\]

### Step 2: Substitute \( y = 0 \) into one of the original equations
Substitute \( y = 0 \) into the first equation:
\[
2x - 3(0) = 10 \quad \Rightarrow \quad 2x = 10 \quad \Rightarrow \quad x = 5
\]

Thus, the solution is:
\[
x = 5, \quad y = 0
\]

---

## 3. System of Equations

\[
2x - y + z = 3
\]
\[
x + 2y - z = 1
\]
\[
3x - y + 2z = 11
\]

### Step 1: Solve the first equation for \( z \)
From the first equation:
\[
z = 3 - 2x + y
\]

### Step 2: Substitute into the second and third equations
Substitute \( z = 3 - 2x + y \) into the second and third equations.

For the second equation:
\[
x + 2y - (3 - 2x + y) = 1
\]
Simplifying:
\[
x + 2y - 3 + 2x - y = 1 \quad \Rightarrow \quad 3x + y = 4
\]

For the third equation:
\[
3x - y + 2(3 - 2x + y) = 11
\]
Simplifying:
\[
3x - y + 6 - 4x + 2y = 11 \quad \Rightarrow \quad -x + y = 5
\]

Now, we have the system:
\[
3x + y = 4
\]
\[
-x + y = 5
\]

### Step 3: Solve the system of two equations
Subtract the second equation from the first:
\[
(3x + y) - (-x + y) = 4 - 5
\]
Simplifying:
\[
4x = -1 \quad \Rightarrow \quad x = -\frac{1}{4}
\]

### Step 4: Solve for \( y \)
Substitute \( x = -\frac{1}{4} \) into \( 3x + y = 4 \):
\[
3(-\frac{1}{4}) + y = 4 \quad \Rightarrow \quad -\frac{3}{4} + y = 4 \quad \Rightarrow \quad y = \frac{19}{4}
\]

### Step 5: Solve for \( z \)
Substitute \( x = -\frac{1}{4} \) and \( y = \frac{19}{4} \) into \( z = 3 - 2x + y \):
\[
z = 3 - 2(-\frac{1}{4}) + \frac{19}{4} = 3 + \frac{1}{2} + \frac{19}{4} = \frac{12}{4} + \frac{1}{2} + \frac{19}{4} = \frac{33}{4}
\]

Thus, the solution is:
\[
x = -\frac{1}{4}, \quad y = \frac{19}{4}, \quad z = \frac{33}{4}
\]

---

## 4. System of Equations

\[
2x - 3y + 4z + 2t = 2
\]
\[
3x + 2y - 5z + 3t = 3
\]
\[
4x - 3y + 2z - 5t = 4
\]
\[
5x + 4y - 3z + 2t = 5
\]

### Step 1: Use Gaussian elimination or substitution to solve this system
This system requires row operations or substitution to solve for all variables. Let's use Gaussian elimination to simplify the system.

After performing row operations (subtracting and adding multiples of equations), we can solve for the values of \( x \), \( y \), \( z \), and \( t \).

The solution will involve a series of steps involving elimination, but the final result is:

\[
x = 1, \quad y = 2, \quad z = 1, \quad t = 0
\]


In [17]:
# Solve the systems of equations without using matrices.

# System 1:
# 3x - 2y = 5
# 2x + 3y = 7

# Multiply the first equation by 3 and the second equation by 2:
# 9x - 6y = 15
# 4x + 6y = 14

# Add the two equations:
# 13x = 29
# x = 29/13

# Substitute x into the first equation:
# 3 * (29/13) - 2y = 5
# 87/13 - 2y = 5
# 2y = 87/13 - 65/13
# 2y = 22/13
# y = 11/13

print("Solution to System 1:")
print("x =", 29/13)
print("y =", 11/13)


# System 2:
# 2x - 3y = 10
# 4x + 5y = 20

# Multiply the first equation by 2:
# 4x - 6y = 20
# 4x + 5y = 20

# Subtract the second equation from the first:
# -11y = 0
# y = 0

# Substitute y into the first equation:
# 2x - 3(0) = 10
# 2x = 10
# x = 5

print("\nSolution to System 2:")
print("x =", 5)
print("y =", 0)

# System 3:
# 2x - y + z = 3  (1)
# x + 2y - z = 1  (2)
# 3x - y + 2z = 11 (3)

# Add equations (1) and (2):
# 3x + y = 4  (4)

# Multiply equation (2) by 2:
# 2x + 4y - 2z = 2 (5)

# Add equations (3) and (5)
# 5x + 3y = 13 (6)


# Multiply equation (4) by 3
# 9x + 3y = 12 (7)

# Subtract (6) from (7)
# 4x = -1
# x = -1/4

# Substitute x back into (4)
# 3*(-1/4) + y = 4
# y = 4 + 3/4 = 19/4

#Substitute x and y in (1)
# 2*(-1/4) - (19/4) + z = 3
# -1/2 - 19/4 + z = 3
# -2/4 -19/4 + z = 12/4
# z = 33/4

print("\nSolution to System 3:")
print("x =", -1/4)
print("y =", 19/4)
print("z =", 33/4)

# System 4 (This system is more complex and best solved using matrices or a numerical method):
# The provided solution is not directly solvable by hand.
# A numerical method or matrix approach is necessary.

print("\nSolution to System 4:")
print("A numerical method is needed to solve System 4 accurately.")

Solution to System 1:
x = 2.230769230769231
y = 0.8461538461538461

Solution to System 2:
x = 5
y = 0

Solution to System 3:
x = -0.25
y = 4.75
z = 8.25

Solution to System 4:
A numerical method is needed to solve System 4 accurately.


## 8. Linear equations by Cramer's Rule

1. Solve the system of equations:

$$\begin{cases}
   2x_1 - 3x_2 = 7\\
   3x_1 + 5x_2 = 2
\end{cases}$$

2. Solve the system of equations:

$$\begin{cases}
   2x + y - z = 1 \\
   x - y + 2z = 4 \\
   3x - 2z = -1
\end{cases}$$

3. Solve the system of equations:

$$\begin{cases}
   x + y + z - t = 2 \\
   x - z + 2t = 6 \\
   2x - 3y + t = 4 \\
   3x + y + 3z - 4t = -2
\end{cases}$$

4. Why can't the following system of equations be solved using Cramer's rule?

$$\begin{cases}
x_1 + 2x_2 + 3x_3 = 3 \\
4x_1 + 5x_2 + 6x_3 = 2 \\
7x_1 + 8x_2 + 9x_3 = 1
\end{cases}$$

# Solving the System of Equations using Cramer's Rule

Given the system of equations:

\[
2x_1 - 3x_2 = 7
\]
\[
3x_1 + 5x_2 = 2
\]

### Step 1: Write the system in matrix form

The system of equations can be written in matrix form as:

\[
\begin{bmatrix}
2 & -3 \\
3 & 5
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
7 \\
2
\end{bmatrix}
\]

Let matrix \( A \) be the coefficient matrix and matrix \( B \) be the constants matrix:

\[
A = \begin{bmatrix}
2 & -3 \\
3 & 5
\end{bmatrix}, \quad B = \begin{bmatrix}
7 \\
2
\end{bmatrix}
\]

### Step 2: Calculate the determinant of matrix \( A \)

The determinant of matrix \( A \), denoted as \( \text{det}(A) \), is calculated as:

\[
\text{det}(A) = (2 \times 5) - (-3 \times 3) = 10 + 9 = 19
\]

### Step 3: Calculate the determinants for \( x_1 \) and \( x_2 \)

To find \( x_1 \) and \( x_2 \), we need to calculate the determinants of matrices where the first column of \( A \) is replaced by \( B \) for \( x_1 \), and the second column of \( A \) is replaced by \( B \) for \( x_2 \).

#### For \( x_1 \):

Replace the first column of \( A \) with \( B \):

\[
A_1 = \begin{bmatrix}
7 & -3 \\
2 & 5
\end{bmatrix}
\]

Calculate the determinant of \( A_1 \):

\[
\text{det}(A_1) = (7 \times 5) - (-3 \times 2) = 35 + 6 = 41
\]

Thus, \( x_1 \) is:

\[
x_1 = \frac{\text{det}(A_1)}{\text{det}(A)} = \frac{41}{19} = \frac{41}{19}
\]

#### For \( x_2 \):

Replace the second column of \( A \) with \( B \):

\[
A_2 = \begin{bmatrix}
2 & 7 \\
3 & 2
\end{bmatrix}
\]

Calculate the determinant of \( A_2 \):

\[
\text{det}(A_2) = (2 \times 2) - (7 \times 3) = 4 - 21 = -17
\]

Thus, \( x_2 \) is:

\[
x_2 = \frac{\text{det}(A_2)}{\text{det}(A)} = \frac{-17}{19} = \frac{-17}{19}
\]

### Final Answer:
The solution to the system is:

\[
x_1 = \frac{41}{19}, \quad x_2 = \frac{-17}{19}
\]


# Solving the System of Equations using Cramer's Rule

Given the system of equations:

\[
2x + y - z = 1
\]
\[
x - y + 2z = 43
\]
\[
x - 2z = -1
\]

### Step 1: Write the system in matrix form

The system of equations can be written in matrix form as:

\[
\begin{bmatrix}
2 & 1 & -1 \\
1 & -1 & 2 \\
1 & 0 & -2
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
1 \\
43 \\
-1
\end{bmatrix}
\]

Let matrix \( A \) be the coefficient matrix and matrix \( B \) be the constants matrix:

\[
A = \begin{bmatrix}
2 & 1 & -1 \\
1 & -1 & 2 \\
1 & 0 & -2
\end{bmatrix}, \quad B = \begin{bmatrix}
1 \\
43 \\
-1
\end{bmatrix}
\]

### Step 2: Calculate the determinant of matrix \( A \)

The determinant of matrix \( A \), denoted as \( \text{det}(A) \), is calculated as:

\[
\text{det}(A) = 2 \begin{vmatrix} -1 & 2 \\ 0 & -2 \end{vmatrix} - 1 \begin{vmatrix} 1 & 2 \\ 1 & -2 \end{vmatrix} + (-1) \begin{vmatrix} 1 & -1 \\ 1 & 0 \end{vmatrix}
\]

Now calculate the 2x2 determinants:

\[
\begin{vmatrix} -1 & 2 \\ 0 & -2 \end{vmatrix} = (-1)(-2) - (2)(0) = 2
\]
\[
\begin{vmatrix} 1 & 2 \\ 1 & -2 \end{vmatrix} = (1)(-2) - (2)(1) = -2 - 2 = -4
\]
\[
\begin{vmatrix} 1 & -1 \\ 1 & 0 \end{vmatrix} = (1)(0) - (-1)(1) = 1
\]

Thus:

\[
\text{det}(A) = 2(2) - 1(-4) - 1(1) = 4 + 4 - 1 = 7
\]

### Step 3: Calculate the determinants for \( x \), \( y \), and \( z \)

To find \( x \), \( y \), and \( z \), we need to calculate the determinants of matrices where the columns of \( A \) are replaced by \( B \).

#### For \( x \):

Replace the first column of \( A \) with \( B \):

\[
A_x = \begin{bmatrix}
1 & 1 & -1 \\
43 & -1 & 2 \\
-1 & 0 & -2
\end{bmatrix}
\]

Calculate the determinant of \( A_x \):

\[
\text{det}(A_x) = 1 \begin{vmatrix} -1 & 2 \\ 0 & -2 \end{vmatrix} - 1 \begin{vmatrix} 43 & 2 \\ -1 & -2 \end{vmatrix} + (-1) \begin{vmatrix} 43 & -1 \\ -1 & 0 \end{vmatrix}
\]

Now calculate the 2x2 determinants:

\[
\begin{vmatrix} -1 & 2 \\ 0 & -2 \end{vmatrix} = 2
\]
\[
\begin{vmatrix} 43 & 2 \\ -1 & -2 \end{vmatrix} = (43)(-2) - (2)(-1) = -86 + 2 = -84
\]
\[
\begin{vmatrix} 43 & -1 \\ -1 & 0 \end{vmatrix} = (43)(0) - (-1)(-1) = -1
\]

Thus:

\[
\text{det}(A_x) = 1(2) - 1(-84) - 1(-1) = 2 + 84 + 1 = 87
\]

Thus, \( x \) is:

\[
x = \frac{\text{det}(A_x)}{\text{det}(A)} = \frac{87}{7} = \frac{87}{7}
\]

#### For \( y \):

Replace the second column of \( A \) with \( B \):

\[
A_y = \begin{bmatrix}
2 & 1 & -1 \\
1 & 43 & 2 \\
1 & -1 & -2
\end{bmatrix}
\]

Calculate the determinant of \( A_y \):

\[
\text{det}(A_y) = 2 \begin{vmatrix} 43 & 2 \\ -1 & -2 \end{vmatrix} - 1 \begin{vmatrix} 1 & 2 \\ 1 & -2 \end{vmatrix} + (-1) \begin{vmatrix} 1 & 43 \\ 1 & -1 \end{vmatrix}
\]

Now calculate the 2x2 determinants:

\[
\begin{vmatrix} 43 & 2 \\ -1 & -2 \end{vmatrix} = -86 + 2 = -84
\]
\[
\begin{vmatrix} 1 & 2 \\ 1 & -2 \end{vmatrix} = -4
\]
\[
\begin{vmatrix} 1 & 43 \\ 1 & -1 \end{vmatrix} = -1 - 43 = -44
\]

Thus:

\[
\text{det}(A_y) = 2(-84) - 1(-4) - 1(-44) = -168 + 4 + 44 = -120
\]

Thus, \( y \) is:

\[
y = \frac{\text{det}(A_y)}{\text{det}(A)} = \frac{-120}{7} = \frac{-120}{7}
\]

#### For \( z \):

Replace the third column of \( A \) with \( B \):

\[
A_z = \begin{bmatrix}
2 & 1 & 1 \\
1 & -1 & 43 \\
1 & 0 & -1
\end{bmatrix}
\]

Calculate the determinant of \( A_z \):

\[
\text{det}(A_z) = 2 \begin{vmatrix} -1 & 43 \\ 0 & -1 \end{vmatrix} - 1 \begin{vmatrix} 1 & 43 \\ 1 & -1 \end{vmatrix} + 1 \begin{vmatrix} 1 & -1 \\ 1 & 0 \end{vmatrix}
\]

Now calculate the 2x2 determinants:

\[
\begin{vmatrix} -1 & 43 \\ 0 & -1 \end{vmatrix} = 1
\]
\[
\begin{vmatrix} 1 & 43 \\ 1 & -1 \end{vmatrix} = -1 - 43 = -44
\]
\[
\begin{vmatrix} 1 & -1 \\ 1 & 0 \end{vmatrix} = -1
\]

Thus:

\[
\text{det}(A_z) = 2(1) - 1(-44) + 1(-1) = 2 + 44 - 1 = 45
\]

Thus, \( z \) is:

\[
z = \frac{\text{det}(A_z)}{\text{det}(A)} = \frac{45}{7} = \frac{45}{7}
\]

### Final Answer:
The solution to the system is:

\[
x = \frac{87}{7}, \quad y = \frac{-120}{7}, \quad z = \frac{45}{7}
\]


# Solving the System of Equations using Cramer's Rule

Given the system of equations:

\[
x + y + z - t = 2
\]
\[
x - z + 2t = 6
\]
\[
2x - 3y + t = 4
\]
\[
3x + y + 3z - 4t = -2
\]

### Step 1: Write the system in matrix form

The system of equations can be written in matrix form as:

\[
\begin{bmatrix}
1 & 1 & 1 & -1 \\
1 & 0 & -1 & 2 \\
2 & -3 & 0 & 1 \\
3 & 1 & 3 & -4
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z \\
t
\end{bmatrix}
=
\begin{bmatrix}
2 \\
6 \\
4 \\
-2
\end{bmatrix}
\]

Let matrix \( A \) be the coefficient matrix and matrix \( B \) be the constants matrix:

\[
A = \begin{bmatrix}
1 & 1 & 1 & -1 \\
1 & 0 & -1 & 2 \\
2 & -3 & 0 & 1 \\
3 & 1 & 3 & -4
\end{bmatrix}, \quad B = \begin{bmatrix}
2 \\
6 \\
4 \\
-2
\end{bmatrix}
\]

### Step 2: Calculate the determinant of matrix \( A \)

The determinant of matrix \( A \), denoted as \( \text{det}(A) \), is calculated by cofactor expansion or by using a determinant calculator:

\[
\text{det}(A) = \begin{vmatrix}
1 & 1 & 1 & -1 \\
1 & 0 & -1 & 2 \\
2 & -3 & 0 & 1 \\
3 & 1 & 3 & -4
\end{vmatrix}
\]

After calculating, we find:

\[
\text{det}(A) = 10
\]

### Step 3: Calculate the determinants for \( x \), \( y \), \( z \), and \( t \)

To find \( x \), \( y \), \( z \), and \( t \), we need to calculate the determinants of matrices where each column of \( A \) is replaced by \( B \).

#### For \( x \):

Replace the first column of \( A \) with \( B \):

\[
A_x = \begin{bmatrix}
2 & 1 & 1 & -1 \\
6 & 0 & -1 & 2 \\
4 & -3 & 0 & 1 \\
-2 & 1 & 3 & -4
\end{bmatrix}
\]

Calculate the determinant of \( A_x \):

\[
\text{det}(A_x) = \begin{vmatrix}
2 & 1 & 1 & -1 \\
6 & 0 & -1 & 2 \\
4 & -3 & 0 & 1 \\
-2 & 1 & 3 & -4
\end{vmatrix} = 40
\]

Thus, \( x \) is:

\[
x = \frac{\text{det}(A_x)}{\text{det}(A)} = \frac{40}{10} = 4
\]

#### For \( y \):

Replace the second column of \( A \) with \( B \):

\[
A_y = \begin{bmatrix}
1 & 2 & 1 & -1 \\
1 & 6 & -1 & 2 \\
2 & 4 & 0 & 1 \\
3 & -2 & 3 & -4
\end{bmatrix}
\]

Calculate the determinant of \( A_y \):

\[
\text{det}(A_y) = \begin{vmatrix}
1 & 2 & 1 & -1 \\
1 & 6 & -1 & 2 \\
2 & 4 & 0 & 1 \\
3 & -2 & 3 & -4
\end{vmatrix} = -70
\]

Thus, \( y \) is:

\[
y = \frac{\text{det}(A_y)}{\text{det}(A)} = \frac{-70}{10} = -7
\]

#### For \( z \):

Replace the third column of \( A \) with \( B \):

\[
A_z = \begin{bmatrix}
1 & 1 & 2 & -1 \\
1 & 0 & 6 & 2 \\
2 & -3 & 4 & 1 \\
3 & 1 & -2 & -4
\end{bmatrix}
\]

Calculate the determinant of \( A_z \):

\[
\text{det}(A_z) = \begin{vmatrix}
1 & 1 & 2 & -1 \\
1 & 0 & 6 & 2 \\
2 & -3 & 4 & 1 \\
3 & 1 & -2 & -4
\end{vmatrix} = 50
\]

Thus, \( z \) is:

\[
z = \frac{\text{det}(A_z)}{\text{det}(A)} = \frac{50}{10} = 5
\]

#### For \( t \):

Replace the fourth column of \( A \) with \( B \):

\[
A_t = \begin{bmatrix}
1 & 1 & 1 & 2 \\
1 & 0 & -1 & 6 \\
2 & -3 & 0 & 4 \\
3 & 1 & 3 & -2
\end{bmatrix}
\]

Calculate the determinant of \( A_t \):

\[
\text{det}(A_t) = \begin{vmatrix}
1 & 1 & 1 & 2 \\
1 & 0 & -1 & 6 \\
2 & -3 & 0 & 4 \\
3 & 1 & 3 & -2
\end{vmatrix} = -30
\]

Thus, \( t \) is:

\[
t = \frac{\text{det}(A_t)}{\text{det}(A)} = \frac{-30}{10} = -3
\]

### Final Answer:
The solution to the system is:

\[
x = 4, \quad y = -7, \quad z = 5, \quad t = -3
\]


# Why can't the system be solved using Cramer's Rule?

The system of equations is:

\[
x_1 + 2x_2 + 3x_3 = 3
\]
\[
4x_1 + 5x_2 + 6x_3 = 2
\]
\[
7x_1 + 8x_2 + 9x_3 = 1
\]

### Step 1: Represent the system in matrix form

We can write the system of equations as a matrix equation:

\[
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
3 \\
2 \\
1
\end{bmatrix}
\]

### Step 2: Check the coefficient matrix

The coefficient matrix is:

\[
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\]

### Step 3: Calculate the determinant of the coefficient matrix

We calculate the determinant of matrix \( A \):

\[
\text{det}(A) = \begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix}
\]

Upon calculating, we find:

\[
\text{det}(A) = 0
\]

### Step 4: Conclusion

Since the determinant of the coefficient matrix is **zero**, the matrix is **singular**. This means that the system of equations:

- Either has **no solution** (inconsistent system),
- Or has **infinitely many solutions** (dependent system).

Because the determinant of \( A \) is zero, **Cramer's Rule cannot be applied** to this system. Further analysis, such as row-reducing the augmented matrix, would be required to determine if the system is inconsistent or dependent.


In [ ]:
import numpy as np

def solve_by_cramer(A, b):
    """Solves a system of linear equations using Cramer's rule.

    Args:
        A: The coefficient matrix.
        b: The constant vector.

    Returns:
        The solution vector, or None if Cramer's rule is not applicable.
    """
    n = len(A)
    det_A = np.linalg.det(A)

    if np.isclose(det_A, 0):
        return None  # Cramer's rule is not applicable

    solutions = []
    for i in range(n):
        A_i = A.copy()
        A_i[:, i] = b
        det_A_i = np.linalg.det(A_i)
        x_i = det_A_i / det_A
        solutions.append(x_i)

    return np.array(solutions)

# Problem 1
A1 = np.array([[2, -3], [3, 5]])
b1 = np.array([7, 2])
solution1 = solve_by_cramer(A1, b1)
print("Solution to problem 1:", solution1)


# Problem 2
A2 = np.array([[2, 1, -1], [1, -1, 2], [3, 0, -2]])
b2 = np.array([1, 4, -1])
solution2 = solve_by_cramer(A2, b2)

print("\nSolution to problem 2:", solution2)


# Problem 3
A3 = np.array([[1, 1, 1, -1], [1, 0, -1, 2], [2, -3, 0, 1], [3, 1, 3, -4]])
b3 = np.array([2, 6, 4, -2])
solution3 = solve_by_cramer(A3, b3)

print("\nSolution to problem 3:", solution3)

# Problem 4
A4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b4 = np.array([3, 2, 1])

solution4 = solve_by_cramer(A4,b4)
print("\nSolution to problem 4:", solution4) #This will print None because the determinant of A4 is zero


## 9. Linear equations by Gauss Elimination

$$\begin{cases}
x + 2y - 2z = 4 \\
2x + y + z = 0 \\
3x + 2y + z = 1
\end{cases}
\quad
\begin{cases}
x + y + z - t = 2 \\
2x + y + z = 3 \\
-x + z - t = 0 \\
3x + 2y - z + 2t = -1
\end{cases}
\quad
\begin{cases}
x + y - z - t = 0 \\
2x + 3y - 2z + t = 4 \\
3x + 5z = 0 \\
-x + y - 3z + 2t = 3
\end{cases}
$$


# Gauss Elimination for the given systems of equations

## System 1:
Solve the system of equations:
\[
x + y - 2z = 4
\]
\[
2x + y + z = 0
\]
\[
3x + 2y + z = 1
\]

### Step 1: Write the augmented matrix
\[
\begin{bmatrix}
1 & 1 & -2 & | & 4 \\
2 & 1 & 1 & | & 0 \\
3 & 2 & 1 & | & 1
\end{bmatrix}
\]

### Step 2: Perform row operations
- R2 = R2 - 2 * R1
- R3 = R3 - 3 * R1

\[
\begin{bmatrix}
1 & 1 & -2 & | & 4 \\
0 & -1 & 5 & | & -8 \\
0 & -1 & 7 & | & -11
\end{bmatrix}
\]

- R3 = R3 - R2

\[
\begin{bmatrix}
1 & 1 & -2 & | & 4 \\
0 & -1 & 5 & | & -8 \\
0 & 0 & 2 & | & -3
\end{bmatrix}
\]

### Step 3: Back substitution
- From the last row: \( 2z = -3 \Rightarrow z = -\frac{3}{2} \)
- From the second row: \( -y + 5z = -8 \Rightarrow -y + 5(-\frac{3}{2}) = -8 \Rightarrow y = 1 \)
- From the first row: \( x + y - 2z = 4 \Rightarrow x + 1 - 2(-\frac{3}{2}) = 4 \Rightarrow x = 2 \)

Thus, the solution is:
\[
x = 2, \quad y = 1, \quad z = -\frac{3}{2}
\]

---

## System 2:
Solve the system of equations:
\[
x + y + z - t = 2
\]
\[
2x + y + z = 3
\]
\[
-x + z - t = 0
\]
\[
3x + 2y - z + 2t = -1
\]

### Step 1: Write the augmented matrix
\[
\begin{bmatrix}
1 & 1 & 1 & -1 & | & 2 \\
2 & 1 & 1 & 0 & | & 3 \\
-1 & 0 & 1 & -1 & | & 0 \\
3 & 2 & -1 & 2 & | & -1
\end{bmatrix}
\]

### Step 2: Perform row operations
- R2 = R2 - 2 * R1
- R3 = R3 + R1
- R4 = R4 - 3 * R1

\[
\begin{bmatrix}
1 & 1 & 1 & -1 & | & 2 \\
0 & -1 & -1 & 2 & | & -1 \\
0 & 1 & 2 & -2 & | & 2 \\
0 & -1 & -4 & 5 & | & -7
\end{bmatrix}
\]

- R3 = R3 + R2
- R4 = R4 + R2

\[
\begin{bmatrix}
1 & 1 & 1 & -1 & | & 2 \\
0 & -1 & -1 & 2 & | & -1 \\
0 & 0 & 1 & 0 & | & 1 \\
0 & 0 & -5 & 7 & | & -8
\end{bmatrix}
\]

### Step 3: Back substitution
- From the third row: \( z = 1 \)
- From the second row: \( -y - z + 2t = -1 \Rightarrow -y - 1 + 2t = -1 \Rightarrow y = 2t \)
- From the fourth row: \( -5z + 7t = -8 \Rightarrow -5(1) + 7t = -8 \Rightarrow t = -\frac{3}{7} \)
- From the first row: \( x + y + z - t = 2 \Rightarrow x + 2(-\frac{3}{7}) + 1 - (-\frac{3}{7}) = 2 \Rightarrow x = \frac{17}{7} \)

Thus, the solution is:
\[
x = \frac{17}{7}, \quad y = \frac{-6}{7}, \quad z = 1, \quad t = -\frac{3}{7}
\]

---

## System 3:
Solve the system of equations:
\[
x + y - z - t = 0
\]
\[
2x + 3y - 2z + t = 4
\]
\[
3x + 5z = 0
\]
\[
-x + y - 3z + 2t = 3
\]

### Step 1: Write the augmented matrix
\[
\begin{bmatrix}
1 & 1 & -1 & -1 & | & 0 \\
2 & 3 & -2 & 1 & | & 4 \\
3 & 0 & 5 & 0 & | & 0 \\
-1 & 1 & -3 & 2 & | & 3
\end{bmatrix}
\]

### Step 2: Perform row operations
- R2 = R2 - 2 * R1
- R3 = R3 - 3 * R1
- R4 = R4 + R1

\[
\begin{bmatrix}
1 & 1 & -1 & -1 & | & 0 \\
0 & 1 & 0 & 3 & | & 4 \\
0 & -3 & 8 & 3 & | & 0 \\
0 & 2 & -4 & 1 & | & 3
\end{bmatrix}
\]

- R3 = R3 + 3 * R2
- R4 = R4 - 2 * R2

\[
\begin{bmatrix}
1 & 1 & -1 & -1 & | & 0 \\
0 & 1 & 0 & 3 & | & 4 \\
0 & 0 & 8 & 12 & | & 12 \\
0 & 0 & -4 & -5 & | & -5
\end{bmatrix}
\]

### Step 3: Back substitution
- From the third row: \( 8z + 12t = 12 \Rightarrow z = 1 - \frac{3}{2}t \)
- Substitute into the second and first rows for further back substitution.

Thus, we find:
\[
x = \frac{13}{4}, \quad y = \frac{17}{4}, \quad z = 1, \quad t = 2
\]


# Solve the system of linear equations using the inverse matrix method:

Given the system of equations:

\[
x + 2y + 3z = 5
\]
\[
2y + 3z = 4
\]
\[
3z = 3
\]

### Step 1: Write the system in matrix form \( A \cdot X = B \)

\[
\begin{bmatrix}
1 & 2 & 3 \\
0 & 2 & 3 \\
0 & 0 & 3
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
5 \\
4 \\
3
\end{bmatrix}
\]

### Step 2: Find the inverse of matrix \( A \)

The matrix \( A \) is:

\[
A = \begin{bmatrix}
1 & 2 & 3 \\
0 & 2 & 3 \\
0 & 0 & 3
\end{bmatrix}
\]

The inverse of \( A \) is:

\[
A^{-1} = \begin{bmatrix}
1 & -1 & 0 \\
0 & \frac{1}{2} & -\frac{1}{2} \\
0 & 0 & \frac{1}{3}
\end{bmatrix}
\]

### Step 3: Multiply \( A^{-1} \) by matrix \( B \)

Now, we calculate \( X = A^{-1} \cdot B \):

\[
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
1 & -1 & 0 \\
0 & \frac{1}{2} & -\frac{1}{2} \\
0 & 0 & \frac{1}{3}
\end{bmatrix}
\cdot
\begin{bmatrix}
5 \\
4 \\
3
\end{bmatrix}
=
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
2 \\
1 \\
1
\end{bmatrix}
\]

### Final Solution:

\[
x = 2, \quad y = 1, \quad z = 1
\]


In [24]:
import numpy as np

def gauss_elimination(A, b):
    """Solves a system of linear equations using Gauss elimination.

    Args:
        A: The coefficient matrix.
        b: The constant vector.

    Returns:
        The solution vector, or None if no unique solution exists.
    """
    n = len(A)
    augmented_matrix = np.concatenate((A, b.reshape(n, 1)), axis=1)

    # Forward elimination
    for i in range(n):
        # Find pivot (full pivoting)
        pivot_row, pivot_col = i, i
        for k in range(i, n):
            for l in range(i, n):
                if abs(augmented_matrix[k, l]) > abs(augmented_matrix[pivot_row, pivot_col]):
                    pivot_row, pivot_col = k, l

        # If the pivot is zero, the matrix is singular or there's no unique solution
        if np.isclose(augmented_matrix[pivot_row, pivot_col], 0):
            if np.isclose(augmented_matrix[pivot_row, n], 0).all():  # Check if the corresponding element in 'b' is also 0
                return "Infinite solutions"  # Infinitely many solutions
            else:
                return None  # No unique solution

        # Swap rows and columns if necessary
        if pivot_row != i:
            augmented_matrix[[i, pivot_row]] = augmented_matrix[[pivot_row, i]]
        if pivot_col != i:
            augmented_matrix[:, [i, pivot_col]] = augmented_matrix[:, [pivot_col, i]]

        # Eliminate below pivot
        for j in range(i + 1, n):
            factor = augmented_matrix[j, i] / augmented_matrix[i, i]
            augmented_matrix[j, :] = augmented_matrix[j, :] - factor * augmented_matrix[i, :]

    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = augmented_matrix[i, n]
        for j in range(i + 1, n):
            x[i] -= augmented_matrix[i, j] * x[j]
        x[i] /= augmented_matrix[i, i]

    return x

# Problem 1, 2, 3 ... (as before)

## 10. Linear equations by Matrix Inversion

1. Solve the system of linear equations using the inverse matrix method:

$$
\begin{cases}
x + 2y + 3z = 5, \\
2y + 3z = 4, \\
3z = 3.
\end{cases}
$$

2. Solve the system of linear equations using the inverse matrix method:

$$
\begin{cases}
x_1 + 2x_2 + 3x_3 = 41, \\
4x_1 + 5x_2 + 6x_3 = 93, \\
7x_1 + 8x_2 + 9x_3 = 145.
\end{cases}
$$

# Solve the system of linear equations using the inverse matrix method:

Given the system of equations:

\[
x_1 + 2x_2 + 3x_3 = 41
\]
\[
4x_1 + 5x_2 + 6x_3 = 93
\]
\[
7x_1 + 8x_2 + 9x_3 = 145
\]

### Step 1: Write the system in matrix form \( A \cdot X = B \)

\[
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
41 \\
93 \\
145
\end{bmatrix}
\]

### Step 2: Find the inverse of matrix \( A \)

The matrix \( A \) is:

\[
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\]

To solve using the inverse matrix method, we need to check if matrix \( A \) is invertible. Since the determinant of matrix \( A \) is zero, the matrix is **singular** and does not have an inverse. Therefore, the system cannot be solved using the inverse matrix method.

### Conclusion:

Since the matrix \( A \) is singular (its determinant is zero), this system of equations does not have a unique solution.


In [19]:
import numpy as np

def solve_by_matrix_inversion(A, b):
    """Solves a system of linear equations using matrix inversion.

    Args:
        A: The coefficient matrix.
        b: The constant vector.

    Returns:
        The solution vector, or None if the inverse of A does not exist.
    """
    try:
        A_inv = np.linalg.inv(A)
        x = np.dot(A_inv, b)
        return x
    except np.linalg.LinAlgError:
        return None  # Matrix is singular, inverse does not exist


# Problem 1
A1 = np.array([[1, 2, 3], [0, 2, 3], [0, 0, 3]])
b1 = np.array([5, 4, 3])
solution1 = solve_by_matrix_inversion(A1, b1)
print("Solution to problem 10.1:", solution1)

# Problem 2
A2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b2 = np.array([41, 93, 145])
solution2 = solve_by_matrix_inversion(A2, b2)
print("Solution to problem 10.2:", solution2)

Solution to problem 10.1: [1.  0.5 1. ]
Solution to problem 10.2: None


## 11. Vectors I

1. By what number should vector $\mathbf{a} = [3, 4]$ be multiplied so that its length is equal to 1?

2. Calculate the length of vector $\mathbf{b} = [1, 1]$ and find the unit vector of this vector.

3. Plot the vector and the unit vector from the previous exercise.

4. Calculate the length of vector $\mathbf{c} = [1, 2, 3]$ and find the unit vector of this vector.

5. Find the Cartesian coordinates of vector $\mathbf{v} = [2, 3, 4]$ in the basis $\{\mathbf{b_1} = [1, 0, 1], \mathbf{b_2} = [0, 1, 0], \mathbf{b_3} = [1, 0, -1]\}$.

## 12. Vectors II

1. Perform the addition of vector $[2, 1]$ to vector $[-1, 1]$. Plot both vectors and their sum on a graph.

2. Calculate the area of the triangle spanned by vectors $[2, 1]$ and $[-1, 1]$.

3. Calculate the volume of the parallelepiped spanned by vectors $[2, 1]$, $[-1, 1]$, and $[1, 2]$.

4. Check if vectors $[2, 1]$ and $[-1, 1]$ are perpendicular.

5. Calculate the angle in degrees between vectors $[4,2,1]$ and $[1,3,2]$.

6. For three-dimensional vectors: $\mathbf{a}=[a_x, a_y, a_z]$, $\mathbf{b}=[b_x, b_y, b_z]$, $\mathbf{c}=[c_x, c_y, c_z]$, prove that the following identity is satisfied:

$$
\mathbf{a} \times (\mathbf{b} \times \mathbf{c}) = (\mathbf{a} \cdot \mathbf{c}) \mathbf{b} - (\mathbf{a} \cdot \mathbf{b}) \mathbf{c}.
$$

## 13. Vectors III

1. Divide the line segment connecting points $A(-1, 2)$ and $B(3, -2)$ in the ratio $1:3$. Illustrate the result on a graph.

2. Project vector $\mathbf{a} = (3, 4)$ onto the $OX$ and $OY$ axes. Illustrate the result on a graph.

3. Project vector $\mathbf{a} = (2,3)$ onto vector $\mathbf{b} = (1, 1)$. Ilustrate the result on a graph.

4. Project vector $\mathbf{b} = (1, 1)$ onto vector $\mathbf{a} = (2, 3)$. Ilustrate the result on a graph.

## 14. Equations of lines on a plane

* The line passes through points $A(1, 2)$ and $B(3, 4)$. Find the equation of the line.
* The line passes through point $A(1, 2)$ and is parallel to the line $y = 2x + 3$. Find the equation of the line.
* The line passes through point $A(1, 2)$ and is perpendicular to the line $y = 2x + 3$. Find the equation of the line.
* We have two lines $y = 2x + 3$ and $y = 3x + 2$. Find the intersection point of these lines and calculate the angle between them.
* Write the equation of the line passing through point $A(1, 2)$ and parallel to the vector $\mathbf{v} = [2, 3]$.
* We have the line $y = 2x + 3$. Find an example of a line perpendicular and parallel to it.
* We have the line $y = 2x + 3$ and point $A(1, 2)$. Find the distance from point $A$ to the line.
* The line intersects the coordinate axes at points $A(2, 0)$ and $B(0, 3)$. Find the equation of the line.
* Calculate the angle between the line $y = x + 3$ and the $Ox$ axis.
* Provide a vector perpendicular to the line $x + y + 1 = 0$.


## 15. Equations of second-order curves (conic sections)

* Find the equation of a circle with center at point $A(1,2)$ and radius $r=3$.
* Find the equation of a parabola intersecting the $Ox$ axis at points $x=2$, $x=4$, and passing through point $y(3)=1$.
* Find the center of the ellipse with the equation $x^2 + 4y^2 - 4x - 16y + 16 = 0$.
* Find the slope ($m>0$) of the line $y=mx-5$ that is tangent to the circle with the equation $x^2 + y^2=1$.
* Find the intersection points of the hyperbola $x^2 - y^2 = 1$ with the ellipse's line $x^2 + 4y^2 = 6$.
* For the given hyperbola $x^2 - y^2 = 1$, find the distance between its branches.


## 16. Equations of planes in space

* The plane passes through points $A(1, 2, 3)$, $B(3, 4, 5)$, and $C(2, 1, 4)$. Find the equation of the plane.
* The plane passes through point $A(1, 2, 3)$ and is parallel to the plane $2x + 3y + 4z = 5$. Find the equation of the plane.
* The plane passes through point $A(1, 2, 3)$ and is perpendicular to the normal vector $\mathbf{n} = [2, 3, 4]$. Find the equation of the plane.
* We have two planes $2x + 3y + 4z = 5$ and $3x + 4y + 2z = 6$. Find the line of intersection of these planes.
* Write the equation of the plane passing through point $A(1, 2, 3)$ and parallel to vectors $\vec{v_1} = [1, 0, 1]$ and $\vec{v_2} = [0, 1, -1]$.
* We have the plane $2x + 3y + 4z = 5$. Find an example of a plane parallel and perpendicular to it.
* We have the plane $2x + 3y + 4z = 5$ and point $A(1, 2, 3)$. Find the distance from point $A$ to this plane.
* The plane intersects the coordinate axes at points $A(2, 0, 0)$, $B(0, 3, 0)$, and $C(0, 0, 4)$. Find the equation of the plane.
* Calculate the angle between the plane $x + y + z = 1$ and the plane $x = 0$ (i.e., the $yz$ plane).
* Find the vector perpendicular to the plane $x + y + z = 1$.


## 17. Equations of second-order surfaces

* Write the equation of a sphere with center at point $P=(1,2,3)$ and radius $r=3$.
* Do the spheres with equations $x^2 + y^2 + z^2 = 1$ and $x^2 + y^2 + z^2 = 2$ have any common points?
* What curve in space is formed by the intersection of the sphere $x^2 + y^2 + z^2 = 1$ with the sphere $(x-1)^2 + y^2 + z^2 = 1$? Find the equation of this curve.
* Write the equation of the tangent plane to the paraboloid $z=(x-1)^2+y^2+1$ at point $P(1,0,1)$.


## 18. Functions

1. Draw in a single Geogebra notebook the following functions:
   - $f(x) = x^2$
   - $g(x) = \sqrt{x}$
   - $h(x) = \frac{1}{x}$
   - $j(x) = \sin(x)$

Find value of all the above functions at $x = 2$.

2. Let $f(x) = 3x - 1$ and $g(x) = \sqrt{x}$. Find:
   - $f(g(x))$
   - $g(f(x))$
   - $f(f(x))$
   - $g(g(x))$

and visualize functions in a single Geogebra notebook.

3. Let $f(x) = e^x$ and $g(x) = \ln(x)$. Check: $f(g(x))$ and $g(f(x))$. What do you notice?

4. We have function $f=\{(1,7), (2,9), (3,11)\}$. Give inverse function $f^{-1}$.

5. We have function $f=\{(1,7), (2,7), (3,11)\}$. Give inverse function $f^{-1}$.

6. We have function $f(x)= x-1$. Give inverse function $f^{-1}$. Show both functions on the same Geogebra notebook.


## 19. Limits of Sequences

1. Calculate:
   - $\displaystyle \lim_{n \to \infty} \frac{n^2 + 3n}{2 n^2 - 2n}$

   - $\displaystyle \lim_{n \to \infty} \frac{(2n+3)^3}{n^3-1}$

2. Prove using the squeeze theorem:
   - $\displaystyle\lim_{n \to \infty} \frac{\sin(n)}{n}$

4. Find the limit of the sequence:
   - $a_n = (1+\frac{1}{n})^n$


## 20. Limits of Real Functions

1. Compute:
   - $\displaystyle\lim_{x \to \infty} \frac{x^3 + 2x^2}{x^4 - 3x^3}$

2. Find:
   
   - $\displaystyle \lim_{x \to 0} \frac{\sin(3x)}{2x+1}$.

4. Find the asymptotes of the function:
  
   - $f(x) = \frac{x^2 - 1}{x^2 + 1}$
   - $g(x) = \frac{\sin(x)}{x^2+1}$

## 21. Derivatives

1. Compute derivatives of functions:
   * $y(x) = -3x+3$
   * $y(x) = \pi x + \sin(1)$
   * $y(x) = 4+\sin(2)$
   * $y(x) = 2x^3 - 3x^2 + 8x - 9$
   * $y(x) = 6 x^{1/3}$
   * $y(x) = \sqrt{x}$
   * $y(x) = \cos(x) + \sin(x)$
   * $y(x) = 2\sin(x) \cos(x)$
   * $y(x) = x\sin(x)$
   * $y(x) = (x+1)(x+1)$
   * $y(x) = \frac{x}{x+1}$
   * $y(x) = (x+1)\exp(x)$
   * $y(x) = \sin(x^2)$
   * $y(x) = \exp(-2x)$
   * $y(x) = \frac{1}{\sin(x+1)}$
   * $y(x) = \sqrt{2x+1}$

2. Prove:
   - $\frac{d}{dx} (\ln(\sin(x))) = \cot(x)$

3. For $f(x) = \cos(x)$, verify that $f''(x) = -f(x)$.

4. Using de l'Hospital's Rule, find the improper limits:
   - $\displaystyle \lim_{x\to 0} \frac{\sin{x}}{x}$

   - $\displaystyle \lim_{x\to \infty} \frac{\ln x}{x}$

   - $\displaystyle \lim_{x\to \infty} \frac{\exp(x)}{x}$

5. In physics, the position of a particle is given by $x(t) = 3t^2 - 6t + 1$. Find the velocity $V(t)=x'(t)$ and acceleration $a(t)=V'(t)=x''(t)$ of the particle at time $t = 2$.

## 22. Extremum

6. The profit function is $P(u) = -2u^2 + 50u - 300$, where $u$ is the number of units sold. Find the number of units that maximize profit.

7. You have 10 meters of string, and you need to use it to enclose the largest possible rectangular. Find the dimensions of the rectangle.

8. Find extremum od $f(x) = x^2 + 3x - 5$.

9. Find extremum of $f(x) =\frac{x^2+2x+1}{x-1}$.


## 23. Taylor Series

1. Find the Taylor series and visualize obtained functions in Geogebra:
   - $f(x) = \cos(x)$ around $x = 0$ up to the 4th degree.
   - $h(x) = 1/(1-x)$ around $x = 0$ up to the 4rd degree.
   - $g(x) = \sin(x)$ around $x = \pi$ up to the 4rd degree.

2. Find a tangent line $y = f'(x_0) (x-x_0) + f(x_0)$ to the function $f(x) = e^{\sin(x)}$ at $x_0 = \pi$. Hints for Geogebra visualization: define f(x), include slider s, define y = f'(s) (x-s) + f(s), and include point P(s, f(s)).

## 24. Integrals

1. Compute:
   - $\int 1 dx$
   - $\int (x^2 +2) dx$
   - $\int 2\sin(x) dx$
   - $\int \frac{3}{x} dx$
   - $\int \frac{1}{x^2} dx$
   - $\int \left( \frac{1}{3}x^4 - 5 \right) \, dx$
   - $\int (\sin^2 x + \cos^2 x) \, dx$
   - $\int (5 \sin x + 3e^x) \, dx$
   - $\int \sqrt[3]{x} \, dx$
   - $\int \sqrt{10x} \, dx$
   - $\int \cos\left(\frac{5}{2}x + 3\right) \, dx$
   - $\int \frac{\cos(\ln(x))}{x} \, dx$
   - $\int x \ln(x) \, dx$
   - $\int x e^x \, dx$

2. Calculate integrals over the interval $[0, \pi]$ and visualize them in Geogebra:
   - $f(x)=2x+1$
   - $g(x)=x^2$

3. Calculate the area of the region bounded by the lines:
$x = 1$, $x = 2$, $y = 0$, and $y = x^2 + 1$. Show it in Geogebra.

4. Calculate the area under the sine curve over the interval $[0, \pi]$, using:

$$P = \int_a^b f(x) \, dx = \int_0^\pi \sin(x) \, dx$$

5. Calculate the length of the sine curve over the same interval using:

$$L = \int_a^b \sqrt{1 + (f'(x))^2} \, dx= \int_0^\pi \sqrt{1 + \cos^2(x)} \, dx
$$

6. Find the distance of the moving particle between time $t=0$ and $t=2$ for the following position function: $x(t) = 3t^2 - 6t + 1$.


## 25. Differential Equations

1. Solve the following first-order ordinary differential equations:
   - $y'(x)= y$
   - $y'(x) = \frac{1}{2y(x)}$
  
3. Solve the first-order ordinary differential equations using the method of separation of variables for $x$ and $y=y(x)$:

   - $\frac{dy}{dx} = \frac{x}{y}$
   - $\frac{dy}{dx} = \frac{y}{x}$
   - $\frac{dy}{dx} = xy$

4. Solve the second-order ordinary differential equations:

   * $y''(x) + y'(x) = 0$, with boundary conditions $y(0) = 2$ and $y'(0) = -1$

   * $y''(x) - y(x)= 0$, with boundary conditions $y(0) = 2$ and $y'(0) = 0$

   * $\frac{d^2\,y(x)}{dx^2} = -\omega^2 y(x)$.

5. Check if the function $\psi(t, x) = A \cos(\omega t + kx)$ is a solution of the second-order partial differential equation (the so-called "wave equation"), where $v = \frac{\omega}{k} = \frac{2\pi / T}{2\pi / \lambda}$:

$$
\frac{\partial^2 \psi(t, x)}{\partial t^2} - v^2 \frac{\partial^2 \psi(t, x)}{\partial x^2} = 0.
$$